# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='time created')),
                ('updated_at', models.DateTimeField(verbose_name='time updated')),
                ('dorm_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('gender_policy', models.CharField(max_length=500)),
                ('bathroom_style', models.CharField(max_length=500)),
                ('room_style', models.CharField(max_length=500)),
                ('amenities', models.CharField(max_length=500)),
                ('class_years', models.CharField(max_length=500)),
                ('comments', models.CharField(max_length=500)),
                ('handicap_access', models.BooleanField()),
                ('custodial_services', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='time created')),
                ('updated_at', models.DateTimeField(verbose_name='time updated')),
                ('rating', models.IntegerField(default=0)),
                ('handicap_rating', models.IntegerField(default=0)),
                ('competetiveness', models.IntegerField(default=0)),
                ('review_id', models.IntegerField(default=0)),
                ('profile_id', models.IntegerField(default=0)),
                ('room_type', models.IntegerField(default=0)),
                ('floor', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=500)),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Dorm')),
            ],
        ),
    ]
