# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20170305_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dorm',
            name='id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='id',
        ),
        migrations.AlterField(
            model_name='dorm',
            name='dorm_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
