# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20170305_1547'),
        ('reviews', '0002_auto_20170305_1546'),
    ]

    operations = [
    ]
