# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-02 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_merge_20170329_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='lat',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='dorm',
            name='long',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='time created'),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='time updated'),
        ),
        migrations.AlterField(
            model_name='review',
            name='competetiveness',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='time created'),
        ),
        migrations.AlterField(
            model_name='review',
            name='floor',
            field=models.CharField(choices=[('Basement', 'Basement'), ('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Fifth', 'Fifth')], default='First', max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='handicap_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Triple', 'Triple'), ('Suite', 'Suite')], default='Single', max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='time updated'),
        ),
    ]
