# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-09 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20170402_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.CharField(default=0, max_length=150),
        ),
    ]
