# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20170409_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'uploads/'),
        ),
    ]
